### ISSUE TITLE
Reference paper

### ISSUE THREAD

**Issue by suryasingh** [bohana/sentlex#1]
@bohana can u please provide some reference paper/material to understand the basic algorithm behind sentlex.

**Comment by bohana** [comment]
Dear Surya,

  The basic algorithm for Sentlex is described in:
  http://arrow.dit.ie/cgi/viewcontent.cgi?article=1119&context=scschcomcon

  And was also used (with minor modifications) in:
  http://arrow.dit.ie/cgi/viewcontent.cgi?article=1119&context=scschcomcon

  Let me know if these help.

Regards,
Bruno.

**Comment by suryasingh** [comment]
@bohana Thanks
