### ISSUE TITLE
Could you please explain how the negator affect result of sentence classification?

### ISSUE THREAD

**Issue by chrisHuxi** [bohana/sentlex#2]
When I try to classify a sentence following README , the result really confuses me:
I input a sentence: _I feel good_. The result seems great.
![image](https://cloud.githubusercontent.com/assets/22554713/21610907/8b6d7306-d205-11e6-98d5-abca0a306511.png)

But, when I add a negator to this sentence, i.e: _I feel not good_. The result as follow:
![image](https://cloud.githubusercontent.com/assets/22554713/21611034/17a49fe8-d206-11e6-8fb9-02607a212bcc.png)

The postive score and negtive score is absolutely the same. 

So, Could you please explain how the negator affect result of sentence classification?

**Comment by bohana** [comment]
Hi Chris. 

Try passing negation=true to classify_document ().

Also annotations=true will add a bit more info to resultdata.

Let me know how that works.

B.

**Comment by chrisHuxi** [comment]
Hi Bohana,

I appreciate your help. And I'm sorry for replying so late, I am terribly busy recently.

And I try the way you told me, result as follow:  


![1](https://cloud.githubusercontent.com/assets/22554713/22171545/58f4e82c-dfcb-11e6-8bcb-feae26de63ca.PNG)

I think it works. : ) 
Thank you very much.
